{% set name = "pyuv" %}
{% set version = "1.4.0" %}
{% set sha256 = "caea2004d1125fe17cbde3c211c8abc72844e9b8dd7dfa007711e98fbc96fbc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-refcnt-fix-over-py310.patch

build:
  number: 1004
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pyuv

about:
  home: https://github.com/saghul/pyuv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'pyuv is a Python module which provides an interface to libuv.'

  description: |
    pyuv is a Python module which provides an interface to libuv. libuv is a high performance asynchronous networking and platform abstraction library.

    libuv is built on top of epoll/kequeue/event ports/etc on Unix and IOCP on Windows systems providing a consistent API on top of them.
  doc_url: https://pyuv.readthedocs.io
  dev_url: https://github.com/saghul/pyuv

extra:
  recipe-maintainers:
    - curtisalexander
